### ISSUE TITLE
OpenDRI newsletter sign-up broken

### ISSUE THREAD

**Issue by jocewest** [GFDRR/opendri-website#33]
We want to make the newsletter sign-up more visible on all pages. 

The small sign-up form in the footer is currently not working, returns an error. Is it possible to fix, and then move (or replicate) the one in the footer to upper right-hand side of the navigation bar?

**Comment by ppasq** [comment]
The newsletter is based on a MailChimp account. @gracedoherty could you please give me some details on this account?

**Comment by cgiovando** [comment]
Sent new code from Mailchimp to @ppasq

**Comment by cgiovando** [comment]
The small signup box in the footer is still broken, with error `Please enter a value`. @ppasq can you please check?

![screen shot 2019-02-13 at 15 54 45](https://user-images.githubusercontent.com/10201533/52720526-0f58cd80-2fa8-11e9-9363-36ef5c1c1f42.jpg)

The form linked from https://opendri.org/about/ is working correctly.

**Comment by cgiovando** [comment]
OK, digging more into Mailchimp I found out that because this box shares the same fields of the bigger signup form linked from the about page, but it only supports one field, then I had to remove the other required fields to make it work. @vdeparday @gracedoherty let me know if that's not an acceptable fix, otherwise we have to either remove this small box or create two separate lists.

**Comment by pzwsk** [comment]
It is now working for me, thanks

![image](https://user-images.githubusercontent.com/2378439/52722563-2e595e80-2fac-11e9-8678-aec489cc406d.png)
